### ISSUE TITLE
Pattern registration through /patterns directory

### ISSUE THREAD

**Issue by huubl** [rtCamp/theme-elementary#259]
Hi,

Just wondering, is there a reason you don't register patterns through the `/patterns` directory?

https://make.wordpress.org/core/2022/05/02/new-features-for-working-with-patterns-and-themes-in-wordpress-6-0/#pattern-directory

**Comment by RahiDroid** [comment]
Hi @huubl 👋 

While the initial work of the theme was being done, the feature wasn't there and was introduced afterwards. The patterns' registration is planned to be using the method you mentioned in the upcoming release of the theme.
