### ISSUE TITLE
Autoload doesn't work after theme search-replace

### ISSUE THREAD

**Issue by RahiDroid** [rtCamp/theme-elementary#37]
## Description
After running the theme initialization either manually or automatically as part of the `npm install` command, the autoloading doesn't work. 

## Steps to Reproduce
- Use `npm run init` and you should be asked for entering the theme name.
- Input the theme name and let it do the search-replace for you.
- Activate the theme in your WP dashboard.

**Comment by thelovekesh** [comment]
It's because of the composer's autoload behavior. Since search-replace alters the classes names composer autoload files are no longer valid.

One solution to fix this is to execute `composer dump-autoload -o` at the end of the init script.
