### ISSUE TITLE
Cleanup task tries to delete nonexistent file './bin/git-init.sh'

### ISSUE THREAD

**Issue by divyarajmasani** [rtCamp/theme-elementary#411]
## Description

After theme setup, CLI asks if the user wants to run a clean-up task. Which essentially removes files that are not needed anymore, like `.git`, `bin` etc.

As part of the cleanup, it also removes the `./bin/git-init.sh` file. After the `init` process is complete, the `npm prepare` script also runs `./bin/git-init.sh`, but it doesn't find it there because, in the cleanup, the file is removed.

## Steps to Reproduce

- Clone Repo
- Run `composer install`
- Finish theme configuration
- On the prompt to cleanup task, choose `y`

## Screenshots

![image](https://github.com/rtCamp/theme-elementary/assets/6906779/831ec3c2-698e-4919-9d4c-05e50a2e903a)

## Additional Information

- `prepare` script: https://github.com/rtCamp/theme-elementary/blob/59d4012e2d5d1ba9df5f3417fa0a143f3d35892e/package.json#L57

**Comment by SH4LIN** [comment]
@divyarajmasani @RahiDroid @thelovekesh 

I have come up with an approach where if we want to execute the `git-init.sh` file we ask for a prompt from the `init.js` file if they want to initialize GitHub or not if they type y, we wil execute the sh file from the `init.js` using the `execFile()` function.

```JS
rl.question('Would you like to initialize GitHub? (y/n) ', (initialize) => {
    if ('n' === initialize.toLowerCase()) {
        console.log(info.warning('\nExiting without initializing GitHub.\n'));
        process.exit(0);
    }

    // Initialize GitHub.
    console.log(info.success('\nInitializing GitHub...'));

    const scriptPath = path.resolve(__dirname, 'git-init.sh');

    console.log('Full path of git-init.sh:', scriptPath);
    // Execute ./github-init.sh
    execFile(scriptPath, (error, stdout, stderr) => {
        if (error) {
            console.log(info.error(`error: ${ error.message }`));
            return;
        }
        if (stderr) {
            console.log(info.error(`stderr: ${ stderr }`));
            return;
        }
        console.log(info.success(`stdout: ${ stdout }`));
        console.log(info.success('\nGitHub initialized!'), '✨');
    });
    rl.close();
});
```

After that in the cleanup process, we will only remove `init.js` and `git-init.sh` from the `bin` folder and keeping only `phpcbf.sh` file so this script from the `package.json` will work `"lint:php:fix": "./bin/phpcbf.sh",`

**Comment by thelovekesh** [comment]
@SH4LIN Moving this logic to `init.js` sounds good to me. But for the sake of other OS compatibility let's remove the dependency from `.sh` executables.

So instead of executing the `git-init.sh`, rewrite the same logic in Nodejs and add that. 

Moreover to the `phpcbf.sh` let's delete the file and update `lint:php:fix` like
```diff
- "lint:php:fix": "./bin/phpcbf.sh"
+ "lint:php:fix": "@php ./vendor/bin/phpcbf"
```

Let's also update the question a little bit, since we will be initializing git :)
```diff
- Would you like to initialize GitHub?
+ Would you like to initialize git?
```
